theme: jekyll-theme-cayman
title: "G3AN: Disentangling Motion and Appearance for Video Generation"
author:
  - name: 'Yaohui Wang'
  - name: Piotr Bilinski
  - name: Francois Bremond
  - name: Antitza Dantcheva
